'''Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, 
the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the 
even-valued terms.'''

#we want to modify this code to allow user to imput the limit of fibonacci to produce and to either sum the odd or even 


def fibonacci(maxValue):
	fiboList = [1, 2]
	while fiboList[-1] <= maxValue:
		nextFibo = fiboList[-1] + fiboList[-2]
		fiboList.append(nextFibo)
	if fiboList[-1] > maxValue:
		fiboList.remove(fiboList[-1])
	return fiboList

def requestAns(request, listOfFibo):
	ans = []
	if request == 'a' or request == 'A':
		opt = " odd values of "
		ans.append(opt)
		for x in listOfFibo:
			if x % 2 != 0:
				ans.append(x)
				

	elif request == 'b' or request == 'B':
		opt = " even values of "
		ans.append(opt)
		for x in listOfFibo:
			if x % 2 == 0:
				ans.append(x)

	elif request == 'c' or request == 'C':
		opt = " odd values totaling to "
		ans.append(opt)
		oddVals = []
		for x in listOfFibo:
			if x % 2 != 0:
				oddVals.append(x)
		totals = sum(oddVals)
		ans.append(totals)


	elif request == 'd' or request == 'D':
		opt = " even values totaling to "
		ans.append(opt)
		evenVals = []
		for x in listOfFibo:
			if x % 2 == 0:
				evenVals.append(x)
		totals = sum(evenVals)
		ans.append(totals)

	else:
		print("The input is not valid, use either lower or upper of a, b, c, d")

	return (ans[0], ans[1:])


#Content starts here
print("\nThis program computes all the fibonacci values below your inputed figure and allows you to perform operations with the values\n.")

#prompt the user for maximum value not to be exceeded by the value inputed
maxValue = int(input("Inpute Max Value:_"))

#if the user imputs q the program is terminated 
while maxValue != 'q':
	if type(maxValue) != int:
		print("Invalid input redo again.\n")
		print("\nRunning the program again press q to quit")
		maxValue = int(input("Inpute Max Value:_"))


	print("Fibonacci Values below " + str(maxValue) + " are :")


	#create alist of fibonacci values dependent on the maxValue inputed as maxValue. The function fibonacci is used here to return the list of fibo
	fiboListing = fibonacci(int(maxValue))
	print("-->", fiboListing, " \n")
	print("\n")


	print("What would you like to do with these values? \n A) Odd values \n B) Even Values \n C) Sum Odd Values \n D) Sum Even Values ")

	request = input("Input your choice (a, b, c, d):_")
	acceptedRequest = ['a', 'A', 'b', 'B', 'c', 'C', 'd', 'D']
	if request not in acceptedRequest:
		print("Invalid input redo again.\n")
		print("\nRunning the program again press q to quit")
		maxValue = int(input("Inpute Max Value:_"))



	requested, result= requestAns(request, fiboListing)

	print("This gives " + requested +  str(result) + "\n")

	for x in range(140):
		print("-", end="")
	print("\nRunning the program again press q to quit")

	maxValue = int(input("Inpute Max Value:_"))

